config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  delete "/tickets/:id", to: "tickets#destroy"
  resources :products, only: [:show, :index]
  # resources :store, only: [:show] do
  resources :tickets, only: [:show, :index, :create, :new] do
    get :assign, to: "tickets#assign", on: :member
    get :assign_later, to: "tickets#assign_later", on: :member
    get :closed, to: "tickets#closed", on: :member
    resources :reviews, only: [:new, :create, :show ]
  end
  get "/tickets/new/ticket_response", to: "tickets#ticket_response", as: 'ticket_response'
  get "/scan/barcode", to: "products#barcode", as: 'barcode'
  post "/scan/barcode", to: "products#barcode"
  get "/scraping", to: "products#scraping"
  # end
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  has_many :reviews


  # def self.scrap(barcode)
  #   url = "https://www.alltricks.fr/Acheter/#{barcode}"
  #   html_file = open(url).read
  #   @html_doc = Nokogiri::HTML(html_file)
  # end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :ticket
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :products
  has_many :users
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :product, optional: true
  validates :section, presence: true
  has_many :reviews, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :store
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

end

app/controllers/products_controller.rb
require 'json'
require 'open-uri'
require 'nokogiri'

class ProductsController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @product = Product.find(params[:id])
  end

  def index
    if params[:query].present?
      file = params[:query].gsub(' ', '+').mb_chars.normalize(:kd).gsub(/[^\x00-\x7F]/n,'').downcase.to_s
      filepath = "https://www.alltricks.fr/ajax-autocomplete/#{file}"
      search = open(filepath).read
      results = JSON.parse(search)
      @products = results['product']
    else
      @products = Product.all
    end
  end

  def scan
  end

  REGEX = /<script type=\"application\/ld\+json\">\n(?<json>.*?\"@type\": \"Product\".*?})\n<\/script>/m

  def scraping
    @barcode = params[:val_barcode]
    url = "https://www.alltricks.fr/Acheter/#{@barcode}"
    html_file = open(url).read
    json = html_file.match(REGEX)[:json].split('<script type="application/ld+json">').last.strip
    data = JSON.parse(json)
    @price = (data['offers'].key?('price') ? data['offers']['price'] : data['offers']['lowPrice'])
    @rating = data['aggregateRating'] && data['aggregateRating']['ratingValue']
    # @rating_count = (data['aggregateRating'].key?('reviewCount') ? data['aggregateRating']['reviewCount'] : "pas d'avis")
    @name = data['name']
    @image = data['image']
    @url = data ['url']
    @description = (data['description'])
    @brand = data['brand']['name']
    @html_doc = Nokogiri::HTML(html_file)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create, :show]
  before_action :set_ticket, only: [:new, :create]
  def show
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.ticket = @ticket
    if @review.save
      redirect_to root_path
    else
      render :new
    end
  end
  private

  def review_params
    params.require(:review).permit(:rating)
  end

  def set_ticket
    @ticket = Ticket.find(params[:ticket_id])
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create, :show, :destroy]

  def index
    @tickets_to_be_assign = Ticket.where(status: 'En attente')
    @tickets_assigned_later = Ticket.where(status: 'Plus tard')
    @tickets_assigned = Ticket.where(status: 'En cours')
    @tickets_closed = Ticket.where(status: 'Terminé')
    @reviews = Review.all
    @average_rating = @reviews.average(:rating)
    @count = Ticket.all.count
  end

  def show
    @ticket = Ticket.find(params[:id])
    @review = Review.new
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.client_identifier = ['Lautaret', 'Planche des belles filles', 'Ventoux', 'Tourmalet', 'Galibier', "Alpe d'Huez", "Aravis", "Aspin", "Croix de Fer", "Izoard", "Télégraphe", "La Madeleine", "Colombière", "Aubisque", "Soulor"].sample
    @ticket.status = 'En attente'
    @ticket.section = params[:commit]
    if @ticket.save
      StoreChannel.broadcast_to(
        Store.first,
        body: render_to_string(partial: "tickets/ticket", locals: { ticket: @ticket, new: true })
      )
        redirect_to ticket_path(@ticket), notice: 'Votre ticket a bien été créé, un vendeur est en chemin'
    else
      render :new
    end
  end

  def assign
    @ticket = Ticket.find(params[:id])
    @ticket.user = current_user
    @ticket.status = 'En cours'
    @ticket.save
    TicketChannel.broadcast_to(@ticket, action: 'refresh')
    StoreChannel.broadcast_to(@store, action: 'refresh')
    redirect_to tickets_path
  end

  def assign_later
    @ticket = Ticket.find(params[:id])
    @ticket.user = current_user
    @ticket.status = 'Plus tard'
    @ticket.save
    TicketChannel.broadcast_to(@ticket, action: 'refresh')
    StoreChannel.broadcast_to(@store, action: 'refresh')
    redirect_to tickets_path
  end

  def closed
    @ticket = Ticket.find(params[:id])
    @ticket.status = 'Terminé'
    @ticket.save
    TicketChannel.broadcast_to(@ticket, action: 'refresh')
    redirect_to tickets_path
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy
    redirect_to new_ticket_path, notice: "Votre demande d'aide à un vendeur à bien été annulée"
  end

  private

  def ticket_params
    params.require(:ticket).permit(:client_identifier, :status, :user_id, :product_id, :section)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_class?(root_path)
    return 'active' if request.path == root_path
    ''
  end
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="152x152" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="apple-mobile-web-app-title" content="Alltricks store">
<meta name="application-name" content="Alltricks store">
<meta name="msapplication-TileColor" content="#da532c">
<%# <meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>
<meta name="theme-color" content="#008bd2">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- <%= analytics_init if GoogleAnalytics.valid_tracker? %> -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render 'application/favicon' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:2158595,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>

  </head>

  <body class="<%= params[:controller] %>_<%= params[:action] %>">
    <div class="flex-grow-1" style="min-height: 400px;">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-container">
  <h2 class="home-text">
    <span style="font-size:50px">Bienvenue</span> <br>dans votre magasin
  </h2>
  <h2 class="home-text">
    <span style="background: white; color: #008bd2; font-size: 51px; padding: 0px 10px">AllTricks !</span>
  </h2>
  <div class="content-homepage">
    <div>
      <%= link_to new_ticket_path, :class => 'btn btn-primary' do %>
      <i class="fas fa-concierge-bell"></i><span style="padding-left: 15px">Appeler un vendeur</span>
      <% end %>
    </div>
    <div style="margin-top: 5vh" >
      <%= link_to barcode_path, :class => 'btn btn-primary' do %>
      <i class="fas fa-qrcode"></i><span style="padding-left: 15px ">Scanner un produit</span>
      <% end %>
    </div>

    <p>
      <button id="togg1">Saisir le code barre manuellement</button>
    </p>
    <div id="d1" style='display:none' class="form-card">
      <form action="/scraping?val_barcode=" method="get">
        <div>
          <input id="val_barcode" name="val_barcode" class="input-form" style="width: 60%">
          <button type="submit" class="btn btn-primary submit">Go</button>
        </div>
      </form>
    </div>
    <div>
      <a href="https://fr.surveymonkey.com/r/QZFFVSW"><i id="survey-text" class="fas fa-praying-hands"> Donnez votre avis !</i></a>
    </div>
  </div>
</div>



<div class="home-lg">
  <div class="container">
    <h2>
      Scannez le QR Code avec votre smartphone pour vous rendre sur <br> l'application mobile <span style="background: white; color: #008bd2; font-size: 33px; padding: 0px 10px; text-shadow: none">AllTricks !</span>
    </h2>
    <a rel='nofollow' href='https://www.qr-code-generator.com' border='0' style='cursor:default'></a>
    <img src='https://chart.googleapis.com/chart?cht=qr&chl=https%3A%2F%2Fwww.anphibia.com%2F&chs=180x180&choe=UTF-8&chld=L|2' alt=''>
    <div class="content-homepage-lg">
      <h2>Scannez un code barre avec l'application mobile <span style="background: white; color: #008bd2; font-size: 33px; padding: 0px 10px; text-shadow: none">AllTricks !</span></h2>
      <div class="barcodes">
        <div class="barcode">
          <%= image_tag("barcode-1.png", :alt => "rss feed", style: 'height:80%;width:auto;') %>
        </div>
        <div class="barcode">
          <%= image_tag("barcode-2.png", :alt => "rss feed", style: 'height:80%;width:auto;') %>
        </div>
        <div class="barcode">
          <%= image_tag("barcode-3.png", :alt => "rss feed", style: 'height:80%;width:auto;') %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/barcode.html.erb
<div class="container" style="padding-top: 10%">
  <div class="title-barcode">
    <h2><span class="title-barcode blue">Scannez</span><br> le code-barre</h2>
    <p>Positionnez le code-barre immobile devant l'appareil photo</p>
  </div>
  <div class="scan-cam">
    <div id="barcode" class="barcode-scan">
      <div id='barcode-scanner'>
      </div>
    </div>
  </div>
  <div class="progress" >
    <div class="progress-bar" role="progressbar" style="width: 0%; transition-duration: 0s" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
    </div>
  </div>
  <div class="scan-form">
    <p><button id="togg1" style="font-size: larger"><strong>Saisir le code manuellement</strong></button></p>
    <div id="d1" style='display:none' class="form-card">
      <form action="/scraping?val_barcode=" method="get">
        <div>
          <input id="val_barcode" name="val_barcode" class="input-form">
          <button type="submit" class="btn btn-primary submit">Go</button>
        </div>
      </form>
    </div>
  </div>
  <div class="appel_vendeur_scan white-survey">
    <%= link_to new_ticket_path, :class => 'btn btn-primary' do %>
      <i class="fas fa-concierge-bell"></i><span style="padding-left: 15px">Appeler un vendeur</span>
    <% end %>
    <div>
      <a href="https://fr.surveymonkey.com/r/QZFFVSW"><i id="survey-text" class="fas fa-praying-hands"> Donnez votre avis !</i></a>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container p-t">
  <div class="search-form b-search">
    <p style="padding-bottom: 22px">Recherchez parmi <br> nos <span style="background:white; color:#008bd2; font-size: 31px; padding: 0px 10px">200000 références</span></p>
    <%= form_tag products_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Entrez votre recherche"
      %>
      <div class="btn-search-form">
        <%= submit_tag "Rechercher", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  <div class="cards-products">
    <% @products.each do |product|  %>
      <% product['skus'].each do |p|%>
        <div class="card-products">
          <img src="https://media.alltricks.com/medium/<%= p['photo'].split('¤')[0] %>" class="card-img-product">
          <div class="card-infos">
            <h4><%= p['Model'] %></h4>
            <div class="card-price">
              <p><%= p['price'] %> €</p>
            </div>
          </div>
        </div>
      <% end %>
    <% end  %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if ["scraping"].include?(params[:action]) %>
  <div class="alltricks-Header flex-navbar">
    <%= link_to root_path do %>
      <i class="fas fa-angle-left"></i><span class="retour">Retour</span>
    <% end %>
    <h2 class="navbar">AllTricks</h2>
    <%= link_to barcode_path do %>
      <i class="fas fa-qrcode"></i>
    <% end %>
  </div>
<% elsif ["barcode", "scan"].include?(params[:action]) %>
  <div class="alltricks-Header">
    <h2 class="navbar">AllTricks</h2>
  </div>
<% elsif ["home"].include?(params[:action]) %>
  <div class="alltricks-Header">
    <h2 class="navbar">AllTricks</h2>
  </div>
<% else %>
  <div class="alltricks-Header flex-navbar">
    <%= link_to root_path do %>
      <i class="fas fa-angle-left"></i><span class="retour">Retour</span>
    <% end %>
    <h2 class="navbar">AllTricks</h2>
    <i class="fas fa-qrcode no-display"></i>
  </div>
<% end %>

app/views/tickets/_ticket.html.erb
<tr class="ticket <%= 'new' if new %>" id="ticket-<%= ticket.id %>">
  <td class="notification"><%= ticket.client_identifier %></td>
  <td><%= ticket.section %></td>
  <td><%= ticket.created_at.strftime("%Hh%M") %></td>
  <td>
    <%= link_to "J'y vais", assign_ticket_path(ticket), class: 'btn btn-primary' %>
    <%= link_to "Plus tard", assign_later_ticket_path(ticket), class: 'btn btn-primary', id: 'action' %>
  </td>

app/views/tickets/_ticket_2.html.erb
<tr class="ticket <%= 'new' if new %>" id="ticket-<%= ticket.id %> ">
  <td><%= ticket.client_identifier %></td>
  <td><%= ticket.section %></td>
  <td><%= ticket.updated_at.strftime("%Hh%M") %></td>
  <td><%= link_to "Clôturer", closed_ticket_path(ticket), class: 'btn btn-primary' %></td>
</div>

app/views/tickets/index.html.erb
<div class="container">
  <div class="d-flex-lg">
    <div class="card card-ticket">
      <h2 class="ticket-title">Tickets en attente</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Client</th>
            <th>Rayon</th>
            <th>Heure</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody id="tickets" data-store-id="<%= current_user.store.id %>">
          <% @tickets_to_be_assign.each do |ticket| %>
            <%= render 'tickets/ticket', ticket: ticket, new: false %>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="card card-ticket">
      <h2 class="ticket-title">Tickets pris par un vendeur</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Client</th>
            <th>Rayon</th>
            <th>Heure</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody id="ticket-show tickets" data-store-id="<%= current_user.store.id %>">
          <% @tickets_assigned_later.each do |ticket| %>
            <%= render 'tickets/ticket_2', ticket: ticket, new: false %>
          <% end %>
        </tbody>
      </table>
      <br>
      <h2 class="ticket-title">Tickets en cours</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Client</th>
            <th>Rayon</th>
            <th>Heure</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody id="ticket-show tickets" data-store-id="<%= current_user.store.id %>">
          <% @tickets_assigned.each do |ticket| %>
            <%= render 'tickets/ticket_2', ticket: ticket, new: false %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="card card-ticket reviews">
    <p>
      <strong>Moyenne de l'équipe</strong><br><% @average_rating.to_i.times do %>
        <i class="fas fa-star"></i>
      <% end %>
      <% (5 - @average_rating.to_i).times do %>
        <i class="far fa-star"></i>
      <% end %> sur <span style="color:#008bd2; font-weight: bold"><%= @reviews.count %></span> avis
    </p>
    <p>
      <strong>Nombre de tickets crées :</strong> <%= @count %>
    </p>
      <p>
      <strong>Temps moyen d'un ticket :</strong>
      <% moyenne = [] %>
      <% @tickets_closed.each do |ticket| %>
            <% moyenne << ticket.updated_at - ticket.created_at %>
      <% end %>
      <p>
        <% timing = (moyenne.inject{ |sum, el| sum + el }.to_f / moyenne.size) %>
        <% unless timing.nan? %>
          <%= Time.at(timing).utc.strftime("%M min %S sec") %>
        <% end %>
      </p>
    </p>
  </div>
  <div id="logout">
    <%= link_to'Se déconnecter', destroy_user_session_path, :class => 'logout btn btn-primary', method: :delete %>
  </div>
</div>

<% if user_signed_in? %>
  <script>
    if(document.querySelector('.notification') != null) {
      Notification.requestPermission()
        .then(permisssion => {
          if (permisssion === 'granted') {
            navigator.serviceWorker.ready;
          }
            var data = 'https://google.com/';
        }).then(() => navigator.serviceWorker.register('service-worker.js'))
          .then(registration => registration.showNotification('👋 magasin Alltricks de Bron', {
            body: 'Un client a besoin de vous, si vous êtes disponible, allez sur l interface vendeur pour vous y positionner',
          }));
    }
  </script>
<% end %>

app/views/tickets/new.html.erb
<div class="background-ticket">
  <div class="container p-t">
    <div class="b-ticket">
      <h2 class="form-ticket-text title">Appelez un</h2>
      <h2 class="form-ticket-text title">
        <span style="background: white; color: #008bd2; font-size: 40px; padding: 0px 10px"> vendeur</span><br> à la rescousse !
      </h2>
      <br>
      <%= simple_form_for(@ticket) do |f| %>
        <%= f.input :client_identifier, :as => :hidden %>
        <div>
          <p class="form-ticket-text body" style="color: white !important">Veuillez indiquer votre rayon :</p>
          <%= f.submit "VTT", class: "btn btn-primary section" %>
          <%= f.submit "Route", class: "btn btn-primary section" %>
          <%= f.submit "Gravel", class: "btn btn-primary section" %>
          <%= f.submit "Electrique", class: "btn btn-primary section" %>
          <%= f.submit "Ville", class: "btn btn-primary section" %>
          <%= f.submit "BMX", class: "btn btn-primary section" %>
          <%= f.submit "Triathlon", class: "btn btn-primary section" %>
          <%= f.submit "Running", class: "btn btn-primary section" %>
          <%= f.submit "Cross training", class: "btn btn-primary section" %>
          <%= f.submit "Outdoor", class: "btn btn-primary section" %>
        </div>
      <% end %>
    </div>
      <div class="button_ticket_scan" style="margin-top: 8.5vh " >
      <%= link_to barcode_path, :class => 'btn btn-primary' do %>
      <i class="fas fa-qrcode"></i><span style="padding-left: 15px ">Scanner un produit</span>
      <% end %>
      <div>
        <a href="https://fr.surveymonkey.com/r/QZFFVSW"><i id="survey-text" class="fas fa-praying-hands"> Donnez votre avis !</i></a>
      </div>
    </div>
  </div>
</div>

app/views/tickets/ticket_response.html.erb
  <% if @ticket.status = 'En attente' %>
    <div class="container ticket-response">
      <div>
        <h1>Votre ticket a bien été créé</h1>
        <h4>Nous allons assigner un vendeur à votre ticket</h4>
      </div>
    </div>

  <% elsif @ticket.status = 'En cours' %>
    <div class="container ticket-response">
      <div>
        <h1>Un vendeur est en chemin</h1>
        <h4>Notre expert vient à votre rescousse</h4>
      </div>
    </div>

  <% else %>
    <div class="container ticket-response">
      <div>
        <h1>Ticket terminé</h1>
        <h4>Nous espérons que notre conseiller à répondu à vos interrogations</h4>
      </div>
    </div>
  <% end %>